# Intoduction to Scikit Learn(SKLearn) 
What we are going to cover
# 0. An End to End Scikit Learn(SKLearn)

0. An End to End Scikit Learn(SKLearn)

In [11]:
import numpy as np

In [1]:
# Get the data ready
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# Create x (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

In [7]:
# Choose the right model and hyper param meters
from sklearn.ensemble import RandomForestClassifier
clf =  RandomForestClassifier(n_estimators=100)

# we keep default hyperparameters

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [14]:
# 3. Fit the model to the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
# 80% training
# 20% testing

In [15]:
clf.fit(X_train, y_train);

In [16]:
# make a prediction
y_label = clf.predict(np.array([0,2,3,4]))

C:\Users\sundh\Desktop\sample_project_1\env\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [18]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
110,64,0,0,180,325,0,1,154,1,0.0,2,0,2
134,41,0,1,126,306,0,1,163,0,0.0,2,0,2
140,51,0,2,120,295,0,0,157,0,0.6,2,0,2
285,46,1,0,140,311,0,1,120,1,1.8,1,2,3
245,48,1,0,124,274,0,0,166,0,0.5,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,41,1,2,130,214,0,0,168,0,2.0,1,0,2
53,44,0,2,108,141,0,1,175,0,0.6,1,0,2
33,54,1,2,125,273,0,0,152,0,0.5,0,1,2
127,67,0,2,152,277,0,1,172,0,0.0,2,1,2
216,62,0,2,130,263,0,1,97,0,1.2,1,1,3

In [19]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
74,43,0,2,122,213,0,1,165,0,0.2,1,0,2
158,58,1,1,125,220,0,1,144,0,0.4,1,4,3
177,64,1,2,140,335,0,1,158,0,0.0,2,0,2
282,59,1,2,126,218,1,1,134,0,2.2,1,1,1
239,35,1,0,126,282,0,0,156,1,0.0,2,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,41,0,2,112,268,0,0,172,1,0.0,2,0,2
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3
62,52,1,3,118,186,0,0,190,0,0.0,1,0,1
266,55,0,0,180,327,0,2,117,1,3.4,1,0,2
199,65,1,0,110,248,0,0,158,0,0.6,2,2,1

In [20]:
y_preds = clf.predict(X_test)
y_preds

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [21]:
y_test

74     1
158    1
177    0
282    0
239    0
      ..
122    1
37     1
62     1
266    0
199    0
Name: target, Length: 61, dtype: int64

In [22]:
# 4. Evaluate the model on training data and test data
clf.score(X_train, y_train)

1.0

In [25]:
clf.score(X_test, y_test)

0.7704918032786885

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [27]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.73      0.73      0.73        26
           1       0.80      0.80      0.80        35

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

In [28]:
confusion_matrix(y_test, y_preds)

array([[19,  7],
       [ 7, 28]], dtype=int64)

In [29]:
accuracy_score(y_test, y_preds)

0.7704918032786885

In [34]:
# Improve a model
# try different amount of n_estimators

np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators ...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}%")
    # this is shortcut in python format string syntax - its round(some_number, 2)
    print("")

Trying model with 10 estimators ...
Model accuracy on test set: 77.05%

Trying model with 20 estimators ...
Model accuracy on test set: 75.41%

Trying model with 30 estimators ...
Model accuracy on test set: 72.13%

Trying model with 40 estimators ...
Model accuracy on test set: 77.05%

Trying model with 50 estimators ...
Model accuracy on test set: 70.49%

Trying model with 60 estimators ...
Model accuracy on test set: 75.41%

Trying model with 70 estimators ...
Model accuracy on test set: 75.41%

Trying model with 80 estimators ...
Model accuracy on test set: 75.41%

Trying model with 90 estimators ...
Model accuracy on test set: 77.05%

In [35]:
# save a model and load it
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

In [36]:
# import a model from .PKL file
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test) # last model we ran it shows that output

0.7704918032786885

In [37]:
# Debugging
# Create x (features matrix)
X = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

In [ ]:
import warnings
warnings.filterwarnings("ignore")
# warnings.filterwarnings("default") - to enable back the warning messages

In [47]:
# Choose the right model and hyper param meters
from sklearn.ensemble import RandomForestClassifier
clf =  RandomForestClassifier()
# above version of sklearn 0.22 this issue fixed - n_estimators=100 by default it will be 100
# n_estimators=100 if we didn't pass anything - it gives warning message
# we keep default hyperparameters

# clf.get_params()

In [48]:
from sklearn.model_selection import train_test_split

X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [49]:
clf.fit(X_train, y_train);

In [50]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
193,60,1,0,145,282,0,0,142,1,2.8,1,2,3
260,66,0,0,178,228,1,1,165,1,1.0,1,2,3
207,60,0,0,150,258,0,0,157,0,2.6,1,2,3
166,67,1,0,120,229,0,0,129,1,2.6,1,2,3
267,49,1,2,118,149,0,0,126,0,0.8,2,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,45,0,1,112,160,0,1,138,0,0.0,1,0,2
93,54,0,1,132,288,1,0,159,1,0.0,2,1,2
37,54,1,2,150,232,0,0,165,0,1.6,2,0,3
264,54,1,0,110,206,0,0,108,1,0.0,1,1,2
272,67,1,0,120,237,0,1,71,0,1.0,1,0,2

In [51]:
import sklearn
sklearn.show_versions()

System:
    python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\sundh\Desktop\sample_project_1\env\python.exe
   machine: Windows-10-10.0.22000-SP0

Python dependencies:
          pip: 21.2.4
   setuptools: 58.0.4
      sklearn: 1.0.2
        numpy: 1.21.5
        scipy: 1.7.3
       Cython: None
       pandas: 1.4.1
   matplotlib: 3.5.1
       joblib: 1.1.0
threadpoolctl: 2.2.0

Built with OpenMP: True